export const LocalKey = {
  STORE_KEY: 'storeUserCredential',
  LOCAL_KEY: {
    MA_NV: 'MA_NV',
    LOG_DN_ID: 'LOG_DN_ID',
    FORM_ID: 'FORM_ID',
    DONVI_ID: 'DONVI_ID',
    NHANVIEN_ID: 'NHANVIEN_ID',
    NGUOIDUNG_ID: 'NGUOIDUNG_ID',
    DVTK_ID: 'DVTK_ID',
    TOKEN: 'TOKEN',
    MODULE_ID: 'MODULE_ID',
    DONVI_ND_ID: 'DONVI_ND_ID',
    TEN_NV: 'TEN_NV',
    CHUCVU: 'CHUCVU',
    LOAINGUOIDUNG: 'LOAINGUOIDUNG',
    AVATAR: 'AVATAR',
  },
  LOCAL_CAPSONHA: {
    HOSO_ID: 'CSN_HOSO_ID',
    DIACHI_ID: 'CSN_DIACHI_ID',
    SOTO: 'CSN_SOTO',
    SOTHUA: 'CSN_SOTHUA',
    IDPHUONGXA: 'CSN_IDPHUONGXA'
  },
  LOCAL_HSG: {
    HSGID: 'A_TN_HSGIAO_ID',
    DVTNID: 'A_TN_HSGDVTN_ID',
    QTID: 'A_TN_HSGQTID_ID',
    KIEUYCID: 'A_TN_HSGKIEUYC_ID',
    TTHS: 'A_TN_HSGTTHS_ID',
    PHUONGXAID: 'A_TN_HSGPHUONGXA_ID'
  },
  LOCAL_CHUYENHOSO: {
    HOPDONG_ID: 'CHS_HOPDONG_ID',
    DVTNID: 'CHS_DVTN_ID',
    QTID: 'CHS_QTID_ID',
    KIEUYCID: 'CHS_KIEUYC_ID'
  },

  LOCAL_DOTCAP: {
    DOTCAP_ID: 'CSN_DOTCAP_ID'
  },

  LOCAL_CRM_DOANHNGHIEP: {
    DOANHNGHIEP_MATD: 'CRM_DN_MATD_ID',
    DOANHNGHIEP_MADN: 'CRM_DN_MADN_ID',
  },

  LOCAL_FORMDONG_P31: {
    P31_CN_TC: 'P31_CN_TC',
    P31_KYC_ID: 'P31_KYC_ID',
    P31_HOPDONG_ID: 'P31_HD',
    P31_KHACHHANG_ID: 'P31_KH',
    P31_MA_HOSO: 'P31_MA_HOSO',
    P31_TEMP_SOTO: 'TTCNQSDD_SOTO',
    P31_TEMP_SOTHUA: 'TTCNQSDD_SOTHUA',
    P31_TEMP_DIENTICH: 'TTCNQSDD_DIENTICH',
    P31_TEMP_MUCDICHSD: 'TTCNQSDD_MUCDICHSD',
    P31_TEMP_HINHTHUCSD: 'TTCNQSDD_HINHTHUCSD',
    P31_TEMP_NGUONGOCSD: 'TTCNQSDD_NGUONGOCSD',
    P31_TEMP_DIACHITEXT: 'TTCNQSDD_DIACHITEXT',
    P31_TEMP_DIACHI_ID: 'TTCNQSDD_DIACHI_ID',
    P31_TEMP_CHIADT_THEOMDSD: 'TTCNQSDD_CHIADT_THEOMDSD'
  },

  LOCAL_THONGBAO: {
    THONGBAO: 'THONG_BAO',
  },
}
